export const INIT = 'INIT';
export const DEBTLIST_CHANGE = 'DEBTLIST_CHANGE';
export const REPAYMENT_INIT = 'REPAYMENT_INIT';
export const REPAYMENT_SUCCESS = 'REPAYMENT_SUCCESS';
export const REPAYMENT_CANCEL = 'REPAYMENT_CANCEL';